apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-words
  labels:
    app: reverse-words
spec:
  template:
    spec:
      imagePullSecrets:
              - name: quay_user_pass
      containers:
      - name: reverse-words
        image: quay.io/g_geo1992/reverse-words:cb1b6fcad6abe6b9c78490a909e23969cae4b512
        env:
        - name: RELEASE
          value: "Production release"
        - $patch: replace
